[de]
contentDir = ""
copyright = "Design By [Wesleystoolbox](https://wesleystoolbox.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
languageName = "EN"
title = "Wesleystoolbox"
weight = 2
[en]
contentDir = "content/english"
copyright = "Design By [Wesleystoolbox](https://wesleystoolbox.com/)"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
languageName = "En"
title = "Wesleystoolbox"
weight = 1
